{
  "openapi": "3.0.0",
  "info": {
    "title": "API_e-commerce",
    "description": "La API proporciona todas las funcionalidades básicas necesarias para administrar un e-commerce. Permite a los usuarios crear cuentas, iniciar sesión, administrar sus perfiles y realizar acciones relacionadas con productos.",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://ecommerce-proyecto-final-nodejs.onrender.com",
      "variables": {}
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "USER"
        ],
        "summary": "crear nuevo usuario",
        "operationId": "createnewuser",
        "parameters": [],
        "requestBody": {
          "description": "Endpoint para crear un nuevo usuario con sus datos básicos. Al momento de crear el usuario, se generará automáticamente un carrito asociado",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/createnewuserrequest"
                  },
                  {
                    "example": {
                      "username": "usuario1",
                      "email": "usuario1@gmail.com",
                      "password": "12345678"
                    }
                  }
                ]
              },
              "example": {
                "username": "usuario2",
                "email": "usuario2@gmail.com",
                "password": "87654321"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/users/1": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "USER"
        ],
        "summary": "Obtener los productos actuales del carrito utilizando el ID del usuario como referencia",
        "operationId": "Getproductsincarbyuserid",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "i1cv9VJ1v6wHxOQ71kAN7FL6EYGX3C_lYtU2MpbdoeNoVc6NWgimaxXsh6nqfeo3nrs2DyL1Zn3AJPLjEEmtafWBmiACMiLrjhiEIj1lsIc0t1mvPhMOG3ip1x1c19-"
            }
          }
        ],
        "requestBody": {
          "description": "Endpoint para obtener los productos de un usuario mediante su ID. Este endpoint devuelve una lista que contiene todos los productos asociados a ese usuario."
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/user/orders/1": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "USER"
        ],
        "summary": "Endpoint para obtener las órdenes de un usuario utilizando su ID.",
        "operationId": "Getordersbyusersid",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzODE3MDEsImV4cCI6MTY4NjM5OTcwMX0.Ppv9PSnXM2oagRAd11VAf3o3eK7cOpXnSfBFmAAPHW1_vKLXyNHQOz6VLBQ7BwVPmNa7F1Gjl6d0vuPlgMgLcQ"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/users/login": {
      "post": {
        "tags": [
          "USER"
        ],
        "summary": "El inicio de sesión del usuario genera un token de autorización necesario.",
        "operationId": "Login",
        "parameters": [],
        "requestBody": {
          "description": "El proceso de inicio de sesión del usuario genera un token de autorización que le otorga acceso a los endpoint protegidos.",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/LoginRequest"
                  },
                  {
                    "example": {
                      "email": "usuario1@gmail.com",
                      "password": "12345678"
                    }
                  }
                ]
              },
              "example": {
                "email": "usuario2@gmail.com",
                "password": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/products": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Crear un producto nuevo",
        "operationId": "CreateProduct",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "Este endpoint se utiliza para la creación de productos. Permite guardar datos como el nombre, imagen, descripción y otros detalles relacionados con el producto.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "XC1wQcLgMgLpuv0d6ljG1F7aNmPVwB7QBLV6zOQHNyLXKv1_WHPAamFBfSnXpOc7K3e3of3aVAxeJN5Xm6iOaijJyuv6dnlJB1F7mM8OeX6IyRrRrGXZahcvJI0nbAjn0ln1c1Eo1XQpAsre1pIGs0YcZ9JNN3uzXL1veAsg9bA"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "encoding": {},
              "schema": {
                "required": [
                  "image",
                  "name",
                  "description",
                  "price",
                  "userId"
                ],
                "type": "object",
                "properties": {
                  "image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "name": {
                    "type": "string",
                    "example": "diseño svg"
                  },
                  "description": {
                    "type": "string",
                    "example": "dibujo cool"
                  },
                  "price": {
                    "type": "integer",
                    "format": "int32",
                    "example": 20
                  },
                  "userId": {
                    "type": "integer",
                    "format": "int32",
                    "example": 1
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Obtener los productos cuya cantidad sea mayor que cero",
        "operationId": "Getproductsmayoresacero",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "sInR5cCI6IkpXVCJ9eyJhbGciOiJIUzUxMiI.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzODE3MDEsImV4cCI6MTY4NjM5OTcwMX0.Ppv9PSnXM2oagRAd11VAf3o3eK7cOpXnSfBFmAAPHW1_vKLXyNHQOz6VLBQ7BwVPmNa7F1Gjl6d0vuPlgMgLcQ"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/products/1": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Editar la descripción de un producto",
        "operationId": "Editdescriptionproduct",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/EditdescriptionproductRequest"
                  },
                  {
                    "example": {
                      "description": "descripcion del producto"
                    }
                  }
                ]
              },
              "example": {
                "description": "descripcion del producto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/productincar/products": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "ProductInCar"
        ],
        "summary": "Agregar al carrito",
        "operationId": "addtocard",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "Endpoint para agregar los productos seleccionados por el usuario al carrito de compras.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "MiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzUx.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzODE3MDEsImV4cCI6MTY4NjM5OTcwMX0.Ppv9PSnXM2oagRAd11VAf3o3eK7cOpXnSfBFmAAPHW1_vKLXyNHQOz6VLBQ7BwVPmNa7F1Gjl6d0vuPlgMgLcQ"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/addtocardrequest"
                  },
                  {
                    "example": {
                      "carId": 1,
                      "productId": 2,
                      "price": 20
                    }
                  }
                ]
              },
              "example": {
                "carId": 1,
                "productId": 2,
                "price": 20
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/orders": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Crea una Orden",
        "operationId": "CreateOrder",
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "description": "Este endpoint permite crear una orden para el usuario.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "UzUxMiIsInR5cCI6IkpXVCJeyJhbGciOiJI9.eyJmaXJzdG5hbWUiOm51bGwsImxhc3RuYW1lIjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJWaW5pY2lvIENoYXZhcnJpYSIsImVtYWlsIjoidmljaGF2YXJyaWEyMUBnbWFpbC5jb20iLCJpYXQiOjE2ODYzNzY1MzIsImV4cCI6MTY4NjM3NjgzMn0.7Mi6H9n8hRYe37mDvTlXC4copN7GpviyN710Nmfzz2aBKIxhgL3cMM7ESp8ReNIW2xRrRZJDR5g-YeogloiiVg"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateOrderRequest"
                  },
                  {
                    "example": {
                      "userId": 1,
                      "totalPrice": 100
                    }
                  }
                ]
              },
              "example": {
                "userId": 1,
                "totalPrice": 100
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/orders/1": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Completa la orden",
        "operationId": "CompletedOrder",
        "parameters": [],
        "requestBody": {
          "description": "Este endpoint se utiliza para completar la orden del usuario.",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CompletedOrderRequest"
                  },
                  {
                    "example": {
                      "carId": 1,
                      "email": "usuario1@gmail.com"
                    }
                  }
                ]
              },
              "example": {
                "carId": 1,
                "email": "usuario1@gmail.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/productInOrder/orders": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Agrega productos a la orden",
        "operationId": "Addproductsinorder",
        "parameters": [],
        "requestBody": {
          "description": "Mediante este endpoint, los productos seleccionados por el usuario se van agregando a la orden en curso.",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/AddproductsinorderRequest"
                  },
                  {
                    "example": {
                      "orderId": 3,
                      "productId": 2,
                      "price": 40,
                      "quantity": 1
                    }
                  }
                ]
              },
              "example": {
                "orderId": 3,
                "productId": 2,
                "price": 40,
                "quantity": 1
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "createnewuserrequest": {
        "title": "createnewuserrequest",
        "required": [
          "username",
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "username": "usuario1",
          "email": "usuario1@gmail.com",
          "password": "12345678"
        }
      },
      "LoginRequest": {
        "title": "LoginRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "usuario1@gmail.com",
          "password": "12345678"
        }
      },
      "addtocardrequest": {
        "title": "addtocardrequest",
        "required": [
          "carId",
          "productId",
          "price"
        ],
        "type": "object",
        "properties": {
          "carId": {
            "type": "integer",
            "format": "int32"
          },
          "productId": {
            "type": "integer",
            "format": "int32"
          },
          "price": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "carId": 1,
          "productId": 2,
          "price": 20
        }
      },
      "CreateOrderRequest": {
        "title": "CreateOrderRequest",
        "required": [
          "userId",
          "totalPrice"
        ],
        "type": "object",
        "properties": {
          "userId": {
            "type": "integer",
            "format": "int32"
          },
          "totalPrice": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "userId": 1,
          "totalPrice": 100
        }
      },
      "CompletedOrderRequest": {
        "title": "CompletedOrderRequest",
        "required": [
          "carId",
          "email"
        ],
        "type": "object",
        "properties": {
          "carId": {
            "type": "integer",
            "format": "int32"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "carId": 1,
          "email": "usuario1@gmail.com"
        }
      },
      "EditdescriptionproductRequest": {
        "title": "EditdescriptionproductRequest",
        "required": [
          "description"
        ],
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          }
        },
        "example": {
          "description": "descripcion del producto"
        }
      },
      "AddproductsinorderRequest": {
        "title": "AddproductsinorderRequest",
        "required": [
          "orderId",
          "productId",
          "price",
          "quantity"
        ],
        "type": "object",
        "properties": {
          "orderId": {
            "type": "integer",
            "format": "int32"
          },
          "productId": {
            "type": "integer",
            "format": "int32"
          },
          "price": {
            "type": "integer",
            "format": "int32"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "orderId": 3,
          "productId": 2,
          "price": 40,
          "quantity": 1
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "tags": [
    {
      "name": "USER"
    },
    {
      "name": "Products"
    },
    {
      "name": "ProductInCar"
    },
    {
      "name": "Orders"
    }
  ]
}
